# Dependencies
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink: pretty

# Setup
title: Wahid's homepage
tagline: 'All my stuff'
description: 'Someday, this will be a million dollar blog :)'
url: http://wahidsadik.github.io/
baseurl: /
excerpt_separator: <!--more-->

author:
  name: 'Wahid Sadik'
  url: https://twitter.com/wsadik

paginate: 5

# Custom vars
version: 0.0.1

github:
  repo: https://github.com/wahidsadik/wahidsadik.github.io
